// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avi_messages.proto

package com.via.avi.messages;

public final class AviMessages {
  private AviMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RawLocationMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string device_id = 1;
    /**
     * <code>required string device_id = 1;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>required string device_id = 1;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>required string device_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    // required int64 ts = 2;
    /**
     * <code>required int64 ts = 2;</code>
     */
    boolean hasTs();
    /**
     * <code>required int64 ts = 2;</code>
     */
    long getTs();

    // optional double latitude = 3;
    /**
     * <code>optional double latitude = 3;</code>
     */
    boolean hasLatitude();
    /**
     * <code>optional double latitude = 3;</code>
     */
    double getLatitude();

    // optional double longitude = 4;
    /**
     * <code>optional double longitude = 4;</code>
     */
    boolean hasLongitude();
    /**
     * <code>optional double longitude = 4;</code>
     */
    double getLongitude();

    // optional float speed = 5;
    /**
     * <code>optional float speed = 5;</code>
     */
    boolean hasSpeed();
    /**
     * <code>optional float speed = 5;</code>
     */
    float getSpeed();

    // optional float bearing = 6;
    /**
     * <code>optional float bearing = 6;</code>
     */
    boolean hasBearing();
    /**
     * <code>optional float bearing = 6;</code>
     */
    float getBearing();

    // optional float accuracy = 7;
    /**
     * <code>optional float accuracy = 7;</code>
     */
    boolean hasAccuracy();
    /**
     * <code>optional float accuracy = 7;</code>
     */
    float getAccuracy();
  }
  /**
   * Protobuf type {@code RawLocationMessage}
   */
  public static final class RawLocationMessage extends
      com.google.protobuf.GeneratedMessage
      implements RawLocationMessageOrBuilder {
    // Use RawLocationMessage.newBuilder() to construct.
    private RawLocationMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RawLocationMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RawLocationMessage defaultInstance;
    public static RawLocationMessage getDefaultInstance() {
      return defaultInstance;
    }

    public RawLocationMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RawLocationMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ts_ = input.readInt64();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              latitude_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              longitude_ = input.readDouble();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              speed_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              bearing_ = input.readFloat();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              accuracy_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.via.avi.messages.AviMessages.internal_static_RawLocationMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.via.avi.messages.AviMessages.internal_static_RawLocationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.via.avi.messages.AviMessages.RawLocationMessage.class, com.via.avi.messages.AviMessages.RawLocationMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<RawLocationMessage> PARSER =
        new com.google.protobuf.AbstractParser<RawLocationMessage>() {
      public RawLocationMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RawLocationMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RawLocationMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string device_id = 1;
    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private java.lang.Object deviceId_;
    /**
     * <code>required string device_id = 1;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string device_id = 1;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string device_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 ts = 2;
    public static final int TS_FIELD_NUMBER = 2;
    private long ts_;
    /**
     * <code>required int64 ts = 2;</code>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 ts = 2;</code>
     */
    public long getTs() {
      return ts_;
    }

    // optional double latitude = 3;
    public static final int LATITUDE_FIELD_NUMBER = 3;
    private double latitude_;
    /**
     * <code>optional double latitude = 3;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double latitude = 3;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    // optional double longitude = 4;
    public static final int LONGITUDE_FIELD_NUMBER = 4;
    private double longitude_;
    /**
     * <code>optional double longitude = 4;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double longitude = 4;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    // optional float speed = 5;
    public static final int SPEED_FIELD_NUMBER = 5;
    private float speed_;
    /**
     * <code>optional float speed = 5;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float speed = 5;</code>
     */
    public float getSpeed() {
      return speed_;
    }

    // optional float bearing = 6;
    public static final int BEARING_FIELD_NUMBER = 6;
    private float bearing_;
    /**
     * <code>optional float bearing = 6;</code>
     */
    public boolean hasBearing() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional float bearing = 6;</code>
     */
    public float getBearing() {
      return bearing_;
    }

    // optional float accuracy = 7;
    public static final int ACCURACY_FIELD_NUMBER = 7;
    private float accuracy_;
    /**
     * <code>optional float accuracy = 7;</code>
     */
    public boolean hasAccuracy() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional float accuracy = 7;</code>
     */
    public float getAccuracy() {
      return accuracy_;
    }

    private void initFields() {
      deviceId_ = "";
      ts_ = 0L;
      latitude_ = 0D;
      longitude_ = 0D;
      speed_ = 0F;
      bearing_ = 0F;
      accuracy_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, ts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, latitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, longitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, speed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, bearing_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, accuracy_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, ts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, latitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, longitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, speed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, bearing_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, accuracy_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.via.avi.messages.AviMessages.RawLocationMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.via.avi.messages.AviMessages.RawLocationMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.via.avi.messages.AviMessages.RawLocationMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.via.avi.messages.AviMessages.RawLocationMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.via.avi.messages.AviMessages.RawLocationMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.via.avi.messages.AviMessages.RawLocationMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.via.avi.messages.AviMessages.RawLocationMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.via.avi.messages.AviMessages.RawLocationMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.via.avi.messages.AviMessages.RawLocationMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.via.avi.messages.AviMessages.RawLocationMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.via.avi.messages.AviMessages.RawLocationMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RawLocationMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.via.avi.messages.AviMessages.RawLocationMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.via.avi.messages.AviMessages.internal_static_RawLocationMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.via.avi.messages.AviMessages.internal_static_RawLocationMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.via.avi.messages.AviMessages.RawLocationMessage.class, com.via.avi.messages.AviMessages.RawLocationMessage.Builder.class);
      }

      // Construct using com.via.avi.messages.AviMessages.RawLocationMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        speed_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        bearing_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        accuracy_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.via.avi.messages.AviMessages.internal_static_RawLocationMessage_descriptor;
      }

      public com.via.avi.messages.AviMessages.RawLocationMessage getDefaultInstanceForType() {
        return com.via.avi.messages.AviMessages.RawLocationMessage.getDefaultInstance();
      }

      public com.via.avi.messages.AviMessages.RawLocationMessage build() {
        com.via.avi.messages.AviMessages.RawLocationMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.via.avi.messages.AviMessages.RawLocationMessage buildPartial() {
        com.via.avi.messages.AviMessages.RawLocationMessage result = new com.via.avi.messages.AviMessages.RawLocationMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.bearing_ = bearing_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.accuracy_ = accuracy_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.via.avi.messages.AviMessages.RawLocationMessage) {
          return mergeFrom((com.via.avi.messages.AviMessages.RawLocationMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.via.avi.messages.AviMessages.RawLocationMessage other) {
        if (other == com.via.avi.messages.AviMessages.RawLocationMessage.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000001;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasBearing()) {
          setBearing(other.getBearing());
        }
        if (other.hasAccuracy()) {
          setAccuracy(other.getAccuracy());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeviceId()) {
          
          return false;
        }
        if (!hasTs()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.via.avi.messages.AviMessages.RawLocationMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.via.avi.messages.AviMessages.RawLocationMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string device_id = 1;
      private java.lang.Object deviceId_ = "";
      /**
       * <code>required string device_id = 1;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }

      // required int64 ts = 2;
      private long ts_ ;
      /**
       * <code>required int64 ts = 2;</code>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 ts = 2;</code>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <code>required int64 ts = 2;</code>
       */
      public Builder setTs(long value) {
        bitField0_ |= 0x00000002;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ts = 2;</code>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ts_ = 0L;
        onChanged();
        return this;
      }

      // optional double latitude = 3;
      private double latitude_ ;
      /**
       * <code>optional double latitude = 3;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double latitude = 3;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>optional double latitude = 3;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000004;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double latitude = 3;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      // optional double longitude = 4;
      private double longitude_ ;
      /**
       * <code>optional double longitude = 4;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double longitude = 4;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>optional double longitude = 4;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000008;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double longitude = 4;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000008);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      // optional float speed = 5;
      private float speed_ ;
      /**
       * <code>optional float speed = 5;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float speed = 5;</code>
       */
      public float getSpeed() {
        return speed_;
      }
      /**
       * <code>optional float speed = 5;</code>
       */
      public Builder setSpeed(float value) {
        bitField0_ |= 0x00000010;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float speed = 5;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000010);
        speed_ = 0F;
        onChanged();
        return this;
      }

      // optional float bearing = 6;
      private float bearing_ ;
      /**
       * <code>optional float bearing = 6;</code>
       */
      public boolean hasBearing() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional float bearing = 6;</code>
       */
      public float getBearing() {
        return bearing_;
      }
      /**
       * <code>optional float bearing = 6;</code>
       */
      public Builder setBearing(float value) {
        bitField0_ |= 0x00000020;
        bearing_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float bearing = 6;</code>
       */
      public Builder clearBearing() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bearing_ = 0F;
        onChanged();
        return this;
      }

      // optional float accuracy = 7;
      private float accuracy_ ;
      /**
       * <code>optional float accuracy = 7;</code>
       */
      public boolean hasAccuracy() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional float accuracy = 7;</code>
       */
      public float getAccuracy() {
        return accuracy_;
      }
      /**
       * <code>optional float accuracy = 7;</code>
       */
      public Builder setAccuracy(float value) {
        bitField0_ |= 0x00000040;
        accuracy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float accuracy = 7;</code>
       */
      public Builder clearAccuracy() {
        bitField0_ = (bitField0_ & ~0x00000040);
        accuracy_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RawLocationMessage)
    }

    static {
      defaultInstance = new RawLocationMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RawLocationMessage)
  }

  public interface ExistMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string device_id = 1;
    /**
     * <code>required string device_id = 1;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>required string device_id = 1;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>required string device_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    // required int64 ts = 2;
    /**
     * <code>required int64 ts = 2;</code>
     */
    boolean hasTs();
    /**
     * <code>required int64 ts = 2;</code>
     */
    long getTs();

    // optional double battery_level = 3;
    /**
     * <code>optional double battery_level = 3;</code>
     */
    boolean hasBatteryLevel();
    /**
     * <code>optional double battery_level = 3;</code>
     */
    double getBatteryLevel();

    // optional .ExistMessage.BatteryPlugged battery_plugged = 4;
    /**
     * <code>optional .ExistMessage.BatteryPlugged battery_plugged = 4;</code>
     */
    boolean hasBatteryPlugged();
    /**
     * <code>optional .ExistMessage.BatteryPlugged battery_plugged = 4;</code>
     */
    com.via.avi.messages.AviMessages.ExistMessage.BatteryPlugged getBatteryPlugged();

    // optional .ExistMessage.BatteryStatus battery_status = 5;
    /**
     * <code>optional .ExistMessage.BatteryStatus battery_status = 5;</code>
     */
    boolean hasBatteryStatus();
    /**
     * <code>optional .ExistMessage.BatteryStatus battery_status = 5;</code>
     */
    com.via.avi.messages.AviMessages.ExistMessage.BatteryStatus getBatteryStatus();

    // optional .ExistMessage.BatteryHealth battery_health = 6;
    /**
     * <code>optional .ExistMessage.BatteryHealth battery_health = 6;</code>
     */
    boolean hasBatteryHealth();
    /**
     * <code>optional .ExistMessage.BatteryHealth battery_health = 6;</code>
     */
    com.via.avi.messages.AviMessages.ExistMessage.BatteryHealth getBatteryHealth();

    // optional int32 battery_temperature = 7;
    /**
     * <code>optional int32 battery_temperature = 7;</code>
     */
    boolean hasBatteryTemperature();
    /**
     * <code>optional int32 battery_temperature = 7;</code>
     */
    int getBatteryTemperature();

    // optional int64 last_gps_time = 8;
    /**
     * <code>optional int64 last_gps_time = 8;</code>
     */
    boolean hasLastGpsTime();
    /**
     * <code>optional int64 last_gps_time = 8;</code>
     */
    long getLastGpsTime();

    // optional double latitude = 9;
    /**
     * <code>optional double latitude = 9;</code>
     */
    boolean hasLatitude();
    /**
     * <code>optional double latitude = 9;</code>
     */
    double getLatitude();

    // optional double longitude = 10;
    /**
     * <code>optional double longitude = 10;</code>
     */
    boolean hasLongitude();
    /**
     * <code>optional double longitude = 10;</code>
     */
    double getLongitude();

    // optional int64 sent_time = 11;
    /**
     * <code>optional int64 sent_time = 11;</code>
     */
    boolean hasSentTime();
    /**
     * <code>optional int64 sent_time = 11;</code>
     */
    long getSentTime();

    // optional bool communication = 12;
    /**
     * <code>optional bool communication = 12;</code>
     */
    boolean hasCommunication();
    /**
     * <code>optional bool communication = 12;</code>
     */
    boolean getCommunication();

    // optional bool mqtt = 13;
    /**
     * <code>optional bool mqtt = 13;</code>
     */
    boolean hasMqtt();
    /**
     * <code>optional bool mqtt = 13;</code>
     */
    boolean getMqtt();

    // optional string app_version = 14;
    /**
     * <code>optional string app_version = 14;</code>
     */
    boolean hasAppVersion();
    /**
     * <code>optional string app_version = 14;</code>
     */
    java.lang.String getAppVersion();
    /**
     * <code>optional string app_version = 14;</code>
     */
    com.google.protobuf.ByteString
        getAppVersionBytes();
  }
  /**
   * Protobuf type {@code ExistMessage}
   */
  public static final class ExistMessage extends
      com.google.protobuf.GeneratedMessage
      implements ExistMessageOrBuilder {
    // Use ExistMessage.newBuilder() to construct.
    private ExistMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExistMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExistMessage defaultInstance;
    public static ExistMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ExistMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExistMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ts_ = input.readInt64();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              batteryLevel_ = input.readDouble();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.via.avi.messages.AviMessages.ExistMessage.BatteryPlugged value = com.via.avi.messages.AviMessages.ExistMessage.BatteryPlugged.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                batteryPlugged_ = value;
              }
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.via.avi.messages.AviMessages.ExistMessage.BatteryStatus value = com.via.avi.messages.AviMessages.ExistMessage.BatteryStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                batteryStatus_ = value;
              }
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.via.avi.messages.AviMessages.ExistMessage.BatteryHealth value = com.via.avi.messages.AviMessages.ExistMessage.BatteryHealth.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                batteryHealth_ = value;
              }
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              batteryTemperature_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              lastGpsTime_ = input.readInt64();
              break;
            }
            case 73: {
              bitField0_ |= 0x00000100;
              latitude_ = input.readDouble();
              break;
            }
            case 81: {
              bitField0_ |= 0x00000200;
              longitude_ = input.readDouble();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              sentTime_ = input.readInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              communication_ = input.readBool();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              mqtt_ = input.readBool();
              break;
            }
            case 114: {
              bitField0_ |= 0x00002000;
              appVersion_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.via.avi.messages.AviMessages.internal_static_ExistMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.via.avi.messages.AviMessages.internal_static_ExistMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.via.avi.messages.AviMessages.ExistMessage.class, com.via.avi.messages.AviMessages.ExistMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ExistMessage> PARSER =
        new com.google.protobuf.AbstractParser<ExistMessage>() {
      public ExistMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExistMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExistMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code ExistMessage.BatteryStatus}
     *
     * <pre>
     * BatteryStatus, BatteryPlugged, BatteryHealth all use the Android
     * values for status numbers.
     * </pre>
     */
    public enum BatteryStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 1;</code>
       */
      UNKNOWN(0, 1),
      /**
       * <code>CHARGING = 2;</code>
       */
      CHARGING(1, 2),
      /**
       * <code>DISCHARGING = 3;</code>
       */
      DISCHARGING(2, 3),
      /**
       * <code>NOT_CHARGING = 4;</code>
       */
      NOT_CHARGING(3, 4),
      /**
       * <code>FULL = 5;</code>
       */
      FULL(4, 5),
      ;

      /**
       * <code>UNKNOWN = 1;</code>
       */
      public static final int UNKNOWN_VALUE = 1;
      /**
       * <code>CHARGING = 2;</code>
       */
      public static final int CHARGING_VALUE = 2;
      /**
       * <code>DISCHARGING = 3;</code>
       */
      public static final int DISCHARGING_VALUE = 3;
      /**
       * <code>NOT_CHARGING = 4;</code>
       */
      public static final int NOT_CHARGING_VALUE = 4;
      /**
       * <code>FULL = 5;</code>
       */
      public static final int FULL_VALUE = 5;


      public final int getNumber() { return value; }

      public static BatteryStatus valueOf(int value) {
        switch (value) {
          case 1: return UNKNOWN;
          case 2: return CHARGING;
          case 3: return DISCHARGING;
          case 4: return NOT_CHARGING;
          case 5: return FULL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<BatteryStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<BatteryStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BatteryStatus>() {
              public BatteryStatus findValueByNumber(int number) {
                return BatteryStatus.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.via.avi.messages.AviMessages.ExistMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final BatteryStatus[] VALUES = values();

      public static BatteryStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private BatteryStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ExistMessage.BatteryStatus)
    }

    /**
     * Protobuf enum {@code ExistMessage.BatteryPlugged}
     */
    public enum BatteryPlugged
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNPLUGGED = 0;</code>
       */
      UNPLUGGED(0, 0),
      /**
       * <code>AC = 1;</code>
       */
      AC(1, 1),
      /**
       * <code>USB = 2;</code>
       */
      USB(2, 2),
      /**
       * <code>WIRELESS = 4;</code>
       */
      WIRELESS(3, 4),
      ;

      /**
       * <code>UNPLUGGED = 0;</code>
       */
      public static final int UNPLUGGED_VALUE = 0;
      /**
       * <code>AC = 1;</code>
       */
      public static final int AC_VALUE = 1;
      /**
       * <code>USB = 2;</code>
       */
      public static final int USB_VALUE = 2;
      /**
       * <code>WIRELESS = 4;</code>
       */
      public static final int WIRELESS_VALUE = 4;


      public final int getNumber() { return value; }

      public static BatteryPlugged valueOf(int value) {
        switch (value) {
          case 0: return UNPLUGGED;
          case 1: return AC;
          case 2: return USB;
          case 4: return WIRELESS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<BatteryPlugged>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<BatteryPlugged>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BatteryPlugged>() {
              public BatteryPlugged findValueByNumber(int number) {
                return BatteryPlugged.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.via.avi.messages.AviMessages.ExistMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final BatteryPlugged[] VALUES = values();

      public static BatteryPlugged valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private BatteryPlugged(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ExistMessage.BatteryPlugged)
    }

    /**
     * Protobuf enum {@code ExistMessage.BatteryHealth}
     */
    public enum BatteryHealth
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN_HEALTH = 1;</code>
       */
      UNKNOWN_HEALTH(0, 1),
      /**
       * <code>GOOD = 2;</code>
       */
      GOOD(1, 2),
      /**
       * <code>OVERHEAT = 3;</code>
       */
      OVERHEAT(2, 3),
      /**
       * <code>DEAD = 4;</code>
       */
      DEAD(3, 4),
      /**
       * <code>OVER_VOLTAGE = 5;</code>
       */
      OVER_VOLTAGE(4, 5),
      /**
       * <code>UNSPECIFIED_FAILURE = 6;</code>
       */
      UNSPECIFIED_FAILURE(5, 6),
      /**
       * <code>COLD = 7;</code>
       */
      COLD(6, 7),
      ;

      /**
       * <code>UNKNOWN_HEALTH = 1;</code>
       */
      public static final int UNKNOWN_HEALTH_VALUE = 1;
      /**
       * <code>GOOD = 2;</code>
       */
      public static final int GOOD_VALUE = 2;
      /**
       * <code>OVERHEAT = 3;</code>
       */
      public static final int OVERHEAT_VALUE = 3;
      /**
       * <code>DEAD = 4;</code>
       */
      public static final int DEAD_VALUE = 4;
      /**
       * <code>OVER_VOLTAGE = 5;</code>
       */
      public static final int OVER_VOLTAGE_VALUE = 5;
      /**
       * <code>UNSPECIFIED_FAILURE = 6;</code>
       */
      public static final int UNSPECIFIED_FAILURE_VALUE = 6;
      /**
       * <code>COLD = 7;</code>
       */
      public static final int COLD_VALUE = 7;


      public final int getNumber() { return value; }

      public static BatteryHealth valueOf(int value) {
        switch (value) {
          case 1: return UNKNOWN_HEALTH;
          case 2: return GOOD;
          case 3: return OVERHEAT;
          case 4: return DEAD;
          case 5: return OVER_VOLTAGE;
          case 6: return UNSPECIFIED_FAILURE;
          case 7: return COLD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<BatteryHealth>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<BatteryHealth>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BatteryHealth>() {
              public BatteryHealth findValueByNumber(int number) {
                return BatteryHealth.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.via.avi.messages.AviMessages.ExistMessage.getDescriptor().getEnumTypes().get(2);
      }

      private static final BatteryHealth[] VALUES = values();

      public static BatteryHealth valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private BatteryHealth(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ExistMessage.BatteryHealth)
    }

    private int bitField0_;
    // required string device_id = 1;
    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private java.lang.Object deviceId_;
    /**
     * <code>required string device_id = 1;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string device_id = 1;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string device_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 ts = 2;
    public static final int TS_FIELD_NUMBER = 2;
    private long ts_;
    /**
     * <code>required int64 ts = 2;</code>
     */
    public boolean hasTs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 ts = 2;</code>
     */
    public long getTs() {
      return ts_;
    }

    // optional double battery_level = 3;
    public static final int BATTERY_LEVEL_FIELD_NUMBER = 3;
    private double batteryLevel_;
    /**
     * <code>optional double battery_level = 3;</code>
     */
    public boolean hasBatteryLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double battery_level = 3;</code>
     */
    public double getBatteryLevel() {
      return batteryLevel_;
    }

    // optional .ExistMessage.BatteryPlugged battery_plugged = 4;
    public static final int BATTERY_PLUGGED_FIELD_NUMBER = 4;
    private com.via.avi.messages.AviMessages.ExistMessage.BatteryPlugged batteryPlugged_;
    /**
     * <code>optional .ExistMessage.BatteryPlugged battery_plugged = 4;</code>
     */
    public boolean hasBatteryPlugged() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .ExistMessage.BatteryPlugged battery_plugged = 4;</code>
     */
    public com.via.avi.messages.AviMessages.ExistMessage.BatteryPlugged getBatteryPlugged() {
      return batteryPlugged_;
    }

    // optional .ExistMessage.BatteryStatus battery_status = 5;
    public static final int BATTERY_STATUS_FIELD_NUMBER = 5;
    private com.via.avi.messages.AviMessages.ExistMessage.BatteryStatus batteryStatus_;
    /**
     * <code>optional .ExistMessage.BatteryStatus battery_status = 5;</code>
     */
    public boolean hasBatteryStatus() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .ExistMessage.BatteryStatus battery_status = 5;</code>
     */
    public com.via.avi.messages.AviMessages.ExistMessage.BatteryStatus getBatteryStatus() {
      return batteryStatus_;
    }

    // optional .ExistMessage.BatteryHealth battery_health = 6;
    public static final int BATTERY_HEALTH_FIELD_NUMBER = 6;
    private com.via.avi.messages.AviMessages.ExistMessage.BatteryHealth batteryHealth_;
    /**
     * <code>optional .ExistMessage.BatteryHealth battery_health = 6;</code>
     */
    public boolean hasBatteryHealth() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .ExistMessage.BatteryHealth battery_health = 6;</code>
     */
    public com.via.avi.messages.AviMessages.ExistMessage.BatteryHealth getBatteryHealth() {
      return batteryHealth_;
    }

    // optional int32 battery_temperature = 7;
    public static final int BATTERY_TEMPERATURE_FIELD_NUMBER = 7;
    private int batteryTemperature_;
    /**
     * <code>optional int32 battery_temperature = 7;</code>
     */
    public boolean hasBatteryTemperature() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 battery_temperature = 7;</code>
     */
    public int getBatteryTemperature() {
      return batteryTemperature_;
    }

    // optional int64 last_gps_time = 8;
    public static final int LAST_GPS_TIME_FIELD_NUMBER = 8;
    private long lastGpsTime_;
    /**
     * <code>optional int64 last_gps_time = 8;</code>
     */
    public boolean hasLastGpsTime() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 last_gps_time = 8;</code>
     */
    public long getLastGpsTime() {
      return lastGpsTime_;
    }

    // optional double latitude = 9;
    public static final int LATITUDE_FIELD_NUMBER = 9;
    private double latitude_;
    /**
     * <code>optional double latitude = 9;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional double latitude = 9;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    // optional double longitude = 10;
    public static final int LONGITUDE_FIELD_NUMBER = 10;
    private double longitude_;
    /**
     * <code>optional double longitude = 10;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional double longitude = 10;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    // optional int64 sent_time = 11;
    public static final int SENT_TIME_FIELD_NUMBER = 11;
    private long sentTime_;
    /**
     * <code>optional int64 sent_time = 11;</code>
     */
    public boolean hasSentTime() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int64 sent_time = 11;</code>
     */
    public long getSentTime() {
      return sentTime_;
    }

    // optional bool communication = 12;
    public static final int COMMUNICATION_FIELD_NUMBER = 12;
    private boolean communication_;
    /**
     * <code>optional bool communication = 12;</code>
     */
    public boolean hasCommunication() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional bool communication = 12;</code>
     */
    public boolean getCommunication() {
      return communication_;
    }

    // optional bool mqtt = 13;
    public static final int MQTT_FIELD_NUMBER = 13;
    private boolean mqtt_;
    /**
     * <code>optional bool mqtt = 13;</code>
     */
    public boolean hasMqtt() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional bool mqtt = 13;</code>
     */
    public boolean getMqtt() {
      return mqtt_;
    }

    // optional string app_version = 14;
    public static final int APP_VERSION_FIELD_NUMBER = 14;
    private java.lang.Object appVersion_;
    /**
     * <code>optional string app_version = 14;</code>
     */
    public boolean hasAppVersion() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional string app_version = 14;</code>
     */
    public java.lang.String getAppVersion() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string app_version = 14;</code>
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      deviceId_ = "";
      ts_ = 0L;
      batteryLevel_ = 0D;
      batteryPlugged_ = com.via.avi.messages.AviMessages.ExistMessage.BatteryPlugged.UNPLUGGED;
      batteryStatus_ = com.via.avi.messages.AviMessages.ExistMessage.BatteryStatus.UNKNOWN;
      batteryHealth_ = com.via.avi.messages.AviMessages.ExistMessage.BatteryHealth.UNKNOWN_HEALTH;
      batteryTemperature_ = 0;
      lastGpsTime_ = 0L;
      latitude_ = 0D;
      longitude_ = 0D;
      sentTime_ = 0L;
      communication_ = false;
      mqtt_ = false;
      appVersion_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, ts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, batteryLevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, batteryPlugged_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, batteryStatus_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, batteryHealth_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, batteryTemperature_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, lastGpsTime_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeDouble(9, latitude_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeDouble(10, longitude_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, sentTime_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBool(12, communication_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBool(13, mqtt_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getAppVersionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, ts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, batteryLevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, batteryPlugged_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, batteryStatus_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, batteryHealth_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, batteryTemperature_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, lastGpsTime_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, latitude_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, longitude_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, sentTime_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, communication_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, mqtt_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getAppVersionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.via.avi.messages.AviMessages.ExistMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.via.avi.messages.AviMessages.ExistMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.via.avi.messages.AviMessages.ExistMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.via.avi.messages.AviMessages.ExistMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.via.avi.messages.AviMessages.ExistMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.via.avi.messages.AviMessages.ExistMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.via.avi.messages.AviMessages.ExistMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.via.avi.messages.AviMessages.ExistMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.via.avi.messages.AviMessages.ExistMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.via.avi.messages.AviMessages.ExistMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.via.avi.messages.AviMessages.ExistMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExistMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.via.avi.messages.AviMessages.ExistMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.via.avi.messages.AviMessages.internal_static_ExistMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.via.avi.messages.AviMessages.internal_static_ExistMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.via.avi.messages.AviMessages.ExistMessage.class, com.via.avi.messages.AviMessages.ExistMessage.Builder.class);
      }

      // Construct using com.via.avi.messages.AviMessages.ExistMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ts_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        batteryLevel_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        batteryPlugged_ = com.via.avi.messages.AviMessages.ExistMessage.BatteryPlugged.UNPLUGGED;
        bitField0_ = (bitField0_ & ~0x00000008);
        batteryStatus_ = com.via.avi.messages.AviMessages.ExistMessage.BatteryStatus.UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000010);
        batteryHealth_ = com.via.avi.messages.AviMessages.ExistMessage.BatteryHealth.UNKNOWN_HEALTH;
        bitField0_ = (bitField0_ & ~0x00000020);
        batteryTemperature_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        lastGpsTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000100);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000200);
        sentTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        communication_ = false;
        bitField0_ = (bitField0_ & ~0x00000800);
        mqtt_ = false;
        bitField0_ = (bitField0_ & ~0x00001000);
        appVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.via.avi.messages.AviMessages.internal_static_ExistMessage_descriptor;
      }

      public com.via.avi.messages.AviMessages.ExistMessage getDefaultInstanceForType() {
        return com.via.avi.messages.AviMessages.ExistMessage.getDefaultInstance();
      }

      public com.via.avi.messages.AviMessages.ExistMessage build() {
        com.via.avi.messages.AviMessages.ExistMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.via.avi.messages.AviMessages.ExistMessage buildPartial() {
        com.via.avi.messages.AviMessages.ExistMessage result = new com.via.avi.messages.AviMessages.ExistMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ts_ = ts_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.batteryLevel_ = batteryLevel_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.batteryPlugged_ = batteryPlugged_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.batteryStatus_ = batteryStatus_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.batteryHealth_ = batteryHealth_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.batteryTemperature_ = batteryTemperature_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.lastGpsTime_ = lastGpsTime_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.sentTime_ = sentTime_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.communication_ = communication_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.mqtt_ = mqtt_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.appVersion_ = appVersion_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.via.avi.messages.AviMessages.ExistMessage) {
          return mergeFrom((com.via.avi.messages.AviMessages.ExistMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.via.avi.messages.AviMessages.ExistMessage other) {
        if (other == com.via.avi.messages.AviMessages.ExistMessage.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000001;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasTs()) {
          setTs(other.getTs());
        }
        if (other.hasBatteryLevel()) {
          setBatteryLevel(other.getBatteryLevel());
        }
        if (other.hasBatteryPlugged()) {
          setBatteryPlugged(other.getBatteryPlugged());
        }
        if (other.hasBatteryStatus()) {
          setBatteryStatus(other.getBatteryStatus());
        }
        if (other.hasBatteryHealth()) {
          setBatteryHealth(other.getBatteryHealth());
        }
        if (other.hasBatteryTemperature()) {
          setBatteryTemperature(other.getBatteryTemperature());
        }
        if (other.hasLastGpsTime()) {
          setLastGpsTime(other.getLastGpsTime());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasSentTime()) {
          setSentTime(other.getSentTime());
        }
        if (other.hasCommunication()) {
          setCommunication(other.getCommunication());
        }
        if (other.hasMqtt()) {
          setMqtt(other.getMqtt());
        }
        if (other.hasAppVersion()) {
          bitField0_ |= 0x00002000;
          appVersion_ = other.appVersion_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeviceId()) {
          
          return false;
        }
        if (!hasTs()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.via.avi.messages.AviMessages.ExistMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.via.avi.messages.AviMessages.ExistMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string device_id = 1;
      private java.lang.Object deviceId_ = "";
      /**
       * <code>required string device_id = 1;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }

      // required int64 ts = 2;
      private long ts_ ;
      /**
       * <code>required int64 ts = 2;</code>
       */
      public boolean hasTs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 ts = 2;</code>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <code>required int64 ts = 2;</code>
       */
      public Builder setTs(long value) {
        bitField0_ |= 0x00000002;
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 ts = 2;</code>
       */
      public Builder clearTs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ts_ = 0L;
        onChanged();
        return this;
      }

      // optional double battery_level = 3;
      private double batteryLevel_ ;
      /**
       * <code>optional double battery_level = 3;</code>
       */
      public boolean hasBatteryLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double battery_level = 3;</code>
       */
      public double getBatteryLevel() {
        return batteryLevel_;
      }
      /**
       * <code>optional double battery_level = 3;</code>
       */
      public Builder setBatteryLevel(double value) {
        bitField0_ |= 0x00000004;
        batteryLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double battery_level = 3;</code>
       */
      public Builder clearBatteryLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        batteryLevel_ = 0D;
        onChanged();
        return this;
      }

      // optional .ExistMessage.BatteryPlugged battery_plugged = 4;
      private com.via.avi.messages.AviMessages.ExistMessage.BatteryPlugged batteryPlugged_ = com.via.avi.messages.AviMessages.ExistMessage.BatteryPlugged.UNPLUGGED;
      /**
       * <code>optional .ExistMessage.BatteryPlugged battery_plugged = 4;</code>
       */
      public boolean hasBatteryPlugged() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .ExistMessage.BatteryPlugged battery_plugged = 4;</code>
       */
      public com.via.avi.messages.AviMessages.ExistMessage.BatteryPlugged getBatteryPlugged() {
        return batteryPlugged_;
      }
      /**
       * <code>optional .ExistMessage.BatteryPlugged battery_plugged = 4;</code>
       */
      public Builder setBatteryPlugged(com.via.avi.messages.AviMessages.ExistMessage.BatteryPlugged value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        batteryPlugged_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ExistMessage.BatteryPlugged battery_plugged = 4;</code>
       */
      public Builder clearBatteryPlugged() {
        bitField0_ = (bitField0_ & ~0x00000008);
        batteryPlugged_ = com.via.avi.messages.AviMessages.ExistMessage.BatteryPlugged.UNPLUGGED;
        onChanged();
        return this;
      }

      // optional .ExistMessage.BatteryStatus battery_status = 5;
      private com.via.avi.messages.AviMessages.ExistMessage.BatteryStatus batteryStatus_ = com.via.avi.messages.AviMessages.ExistMessage.BatteryStatus.UNKNOWN;
      /**
       * <code>optional .ExistMessage.BatteryStatus battery_status = 5;</code>
       */
      public boolean hasBatteryStatus() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .ExistMessage.BatteryStatus battery_status = 5;</code>
       */
      public com.via.avi.messages.AviMessages.ExistMessage.BatteryStatus getBatteryStatus() {
        return batteryStatus_;
      }
      /**
       * <code>optional .ExistMessage.BatteryStatus battery_status = 5;</code>
       */
      public Builder setBatteryStatus(com.via.avi.messages.AviMessages.ExistMessage.BatteryStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        batteryStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ExistMessage.BatteryStatus battery_status = 5;</code>
       */
      public Builder clearBatteryStatus() {
        bitField0_ = (bitField0_ & ~0x00000010);
        batteryStatus_ = com.via.avi.messages.AviMessages.ExistMessage.BatteryStatus.UNKNOWN;
        onChanged();
        return this;
      }

      // optional .ExistMessage.BatteryHealth battery_health = 6;
      private com.via.avi.messages.AviMessages.ExistMessage.BatteryHealth batteryHealth_ = com.via.avi.messages.AviMessages.ExistMessage.BatteryHealth.UNKNOWN_HEALTH;
      /**
       * <code>optional .ExistMessage.BatteryHealth battery_health = 6;</code>
       */
      public boolean hasBatteryHealth() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .ExistMessage.BatteryHealth battery_health = 6;</code>
       */
      public com.via.avi.messages.AviMessages.ExistMessage.BatteryHealth getBatteryHealth() {
        return batteryHealth_;
      }
      /**
       * <code>optional .ExistMessage.BatteryHealth battery_health = 6;</code>
       */
      public Builder setBatteryHealth(com.via.avi.messages.AviMessages.ExistMessage.BatteryHealth value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        batteryHealth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ExistMessage.BatteryHealth battery_health = 6;</code>
       */
      public Builder clearBatteryHealth() {
        bitField0_ = (bitField0_ & ~0x00000020);
        batteryHealth_ = com.via.avi.messages.AviMessages.ExistMessage.BatteryHealth.UNKNOWN_HEALTH;
        onChanged();
        return this;
      }

      // optional int32 battery_temperature = 7;
      private int batteryTemperature_ ;
      /**
       * <code>optional int32 battery_temperature = 7;</code>
       */
      public boolean hasBatteryTemperature() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 battery_temperature = 7;</code>
       */
      public int getBatteryTemperature() {
        return batteryTemperature_;
      }
      /**
       * <code>optional int32 battery_temperature = 7;</code>
       */
      public Builder setBatteryTemperature(int value) {
        bitField0_ |= 0x00000040;
        batteryTemperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 battery_temperature = 7;</code>
       */
      public Builder clearBatteryTemperature() {
        bitField0_ = (bitField0_ & ~0x00000040);
        batteryTemperature_ = 0;
        onChanged();
        return this;
      }

      // optional int64 last_gps_time = 8;
      private long lastGpsTime_ ;
      /**
       * <code>optional int64 last_gps_time = 8;</code>
       */
      public boolean hasLastGpsTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 last_gps_time = 8;</code>
       */
      public long getLastGpsTime() {
        return lastGpsTime_;
      }
      /**
       * <code>optional int64 last_gps_time = 8;</code>
       */
      public Builder setLastGpsTime(long value) {
        bitField0_ |= 0x00000080;
        lastGpsTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 last_gps_time = 8;</code>
       */
      public Builder clearLastGpsTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        lastGpsTime_ = 0L;
        onChanged();
        return this;
      }

      // optional double latitude = 9;
      private double latitude_ ;
      /**
       * <code>optional double latitude = 9;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional double latitude = 9;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>optional double latitude = 9;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000100;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double latitude = 9;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000100);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      // optional double longitude = 10;
      private double longitude_ ;
      /**
       * <code>optional double longitude = 10;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional double longitude = 10;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>optional double longitude = 10;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000200;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double longitude = 10;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000200);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      // optional int64 sent_time = 11;
      private long sentTime_ ;
      /**
       * <code>optional int64 sent_time = 11;</code>
       */
      public boolean hasSentTime() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int64 sent_time = 11;</code>
       */
      public long getSentTime() {
        return sentTime_;
      }
      /**
       * <code>optional int64 sent_time = 11;</code>
       */
      public Builder setSentTime(long value) {
        bitField0_ |= 0x00000400;
        sentTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sent_time = 11;</code>
       */
      public Builder clearSentTime() {
        bitField0_ = (bitField0_ & ~0x00000400);
        sentTime_ = 0L;
        onChanged();
        return this;
      }

      // optional bool communication = 12;
      private boolean communication_ ;
      /**
       * <code>optional bool communication = 12;</code>
       */
      public boolean hasCommunication() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional bool communication = 12;</code>
       */
      public boolean getCommunication() {
        return communication_;
      }
      /**
       * <code>optional bool communication = 12;</code>
       */
      public Builder setCommunication(boolean value) {
        bitField0_ |= 0x00000800;
        communication_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool communication = 12;</code>
       */
      public Builder clearCommunication() {
        bitField0_ = (bitField0_ & ~0x00000800);
        communication_ = false;
        onChanged();
        return this;
      }

      // optional bool mqtt = 13;
      private boolean mqtt_ ;
      /**
       * <code>optional bool mqtt = 13;</code>
       */
      public boolean hasMqtt() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional bool mqtt = 13;</code>
       */
      public boolean getMqtt() {
        return mqtt_;
      }
      /**
       * <code>optional bool mqtt = 13;</code>
       */
      public Builder setMqtt(boolean value) {
        bitField0_ |= 0x00001000;
        mqtt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool mqtt = 13;</code>
       */
      public Builder clearMqtt() {
        bitField0_ = (bitField0_ & ~0x00001000);
        mqtt_ = false;
        onChanged();
        return this;
      }

      // optional string app_version = 14;
      private java.lang.Object appVersion_ = "";
      /**
       * <code>optional string app_version = 14;</code>
       */
      public boolean hasAppVersion() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional string app_version = 14;</code>
       */
      public java.lang.String getAppVersion() {
        java.lang.Object ref = appVersion_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          appVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string app_version = 14;</code>
       */
      public com.google.protobuf.ByteString
          getAppVersionBytes() {
        java.lang.Object ref = appVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string app_version = 14;</code>
       */
      public Builder setAppVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        appVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string app_version = 14;</code>
       */
      public Builder clearAppVersion() {
        bitField0_ = (bitField0_ & ~0x00002000);
        appVersion_ = getDefaultInstance().getAppVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string app_version = 14;</code>
       */
      public Builder setAppVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        appVersion_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ExistMessage)
    }

    static {
      defaultInstance = new ExistMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ExistMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RawLocationMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RawLocationMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ExistMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ExistMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022avi_messages.proto\"\212\001\n\022RawLocationMess" +
      "age\022\021\n\tdevice_id\030\001 \002(\t\022\n\n\002ts\030\002 \002(\003\022\020\n\010la" +
      "titude\030\003 \001(\001\022\021\n\tlongitude\030\004 \001(\001\022\r\n\005speed" +
      "\030\005 \001(\002\022\017\n\007bearing\030\006 \001(\002\022\020\n\010accuracy\030\007 \001(" +
      "\002\"\240\005\n\014ExistMessage\022\021\n\tdevice_id\030\001 \002(\t\022\n\n" +
      "\002ts\030\002 \002(\003\022\025\n\rbattery_level\030\003 \001(\001\0225\n\017batt" +
      "ery_plugged\030\004 \001(\0162\034.ExistMessage.Battery" +
      "Plugged\0223\n\016battery_status\030\005 \001(\0162\033.ExistM" +
      "essage.BatteryStatus\0223\n\016battery_health\030\006" +
      " \001(\0162\033.ExistMessage.BatteryHealth\022\033\n\023bat",
      "tery_temperature\030\007 \001(\005\022\025\n\rlast_gps_time\030" +
      "\010 \001(\003\022\020\n\010latitude\030\t \001(\001\022\021\n\tlongitude\030\n \001" +
      "(\001\022\021\n\tsent_time\030\013 \001(\003\022\025\n\rcommunication\030\014" +
      " \001(\010\022\014\n\004mqtt\030\r \001(\010\022\023\n\013app_version\030\016 \001(\t\"" +
      "W\n\rBatteryStatus\022\013\n\007UNKNOWN\020\001\022\014\n\010CHARGIN" +
      "G\020\002\022\017\n\013DISCHARGING\020\003\022\020\n\014NOT_CHARGING\020\004\022\010" +
      "\n\004FULL\020\005\">\n\016BatteryPlugged\022\r\n\tUNPLUGGED\020" +
      "\000\022\006\n\002AC\020\001\022\007\n\003USB\020\002\022\014\n\010WIRELESS\020\004\"z\n\rBatt" +
      "eryHealth\022\022\n\016UNKNOWN_HEALTH\020\001\022\010\n\004GOOD\020\002\022" +
      "\014\n\010OVERHEAT\020\003\022\010\n\004DEAD\020\004\022\020\n\014OVER_VOLTAGE\020",
      "\005\022\027\n\023UNSPECIFIED_FAILURE\020\006\022\010\n\004COLD\020\007B#\n\024" +
      "com.via.avi.messagesB\013AviMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RawLocationMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RawLocationMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RawLocationMessage_descriptor,
              new java.lang.String[] { "DeviceId", "Ts", "Latitude", "Longitude", "Speed", "Bearing", "Accuracy", });
          internal_static_ExistMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ExistMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ExistMessage_descriptor,
              new java.lang.String[] { "DeviceId", "Ts", "BatteryLevel", "BatteryPlugged", "BatteryStatus", "BatteryHealth", "BatteryTemperature", "LastGpsTime", "Latitude", "Longitude", "SentTime", "Communication", "Mqtt", "AppVersion", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
