# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: avi_messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='avi_messages.proto',
  package='',
  serialized_pb='\n\x12\x61vi_messages.proto\"\x8a\x01\n\x12RawLocationMessage\x12\x11\n\tdevice_id\x18\x01 \x02(\t\x12\n\n\x02ts\x18\x02 \x02(\x03\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\r\n\x05speed\x18\x05 \x01(\x02\x12\x0f\n\x07\x62\x65\x61ring\x18\x06 \x01(\x02\x12\x10\n\x08\x61\x63\x63uracy\x18\x07 \x01(\x02\"\xa0\x05\n\x0c\x45xistMessage\x12\x11\n\tdevice_id\x18\x01 \x02(\t\x12\n\n\x02ts\x18\x02 \x02(\x03\x12\x15\n\rbattery_level\x18\x03 \x01(\x01\x12\x35\n\x0f\x62\x61ttery_plugged\x18\x04 \x01(\x0e\x32\x1c.ExistMessage.BatteryPlugged\x12\x33\n\x0e\x62\x61ttery_status\x18\x05 \x01(\x0e\x32\x1b.ExistMessage.BatteryStatus\x12\x33\n\x0e\x62\x61ttery_health\x18\x06 \x01(\x0e\x32\x1b.ExistMessage.BatteryHealth\x12\x1b\n\x13\x62\x61ttery_temperature\x18\x07 \x01(\x05\x12\x15\n\rlast_gps_time\x18\x08 \x01(\x03\x12\x10\n\x08latitude\x18\t \x01(\x01\x12\x11\n\tlongitude\x18\n \x01(\x01\x12\x11\n\tsent_time\x18\x0b \x01(\x03\x12\x15\n\rcommunication\x18\x0c \x01(\x08\x12\x0c\n\x04mqtt\x18\r \x01(\x08\x12\x13\n\x0b\x61pp_version\x18\x0e \x01(\t\"W\n\rBatteryStatus\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x0c\n\x08\x43HARGING\x10\x02\x12\x0f\n\x0b\x44ISCHARGING\x10\x03\x12\x10\n\x0cNOT_CHARGING\x10\x04\x12\x08\n\x04\x46ULL\x10\x05\">\n\x0e\x42\x61tteryPlugged\x12\r\n\tUNPLUGGED\x10\x00\x12\x06\n\x02\x41\x43\x10\x01\x12\x07\n\x03USB\x10\x02\x12\x0c\n\x08WIRELESS\x10\x04\"z\n\rBatteryHealth\x12\x12\n\x0eUNKNOWN_HEALTH\x10\x01\x12\x08\n\x04GOOD\x10\x02\x12\x0c\n\x08OVERHEAT\x10\x03\x12\x08\n\x04\x44\x45\x41\x44\x10\x04\x12\x10\n\x0cOVER_VOLTAGE\x10\x05\x12\x17\n\x13UNSPECIFIED_FAILURE\x10\x06\x12\x08\n\x04\x43OLD\x10\x07\x42#\n\x14\x63om.via.avi.messagesB\x0b\x41viMessages')



_EXISTMESSAGE_BATTERYSTATUS = _descriptor.EnumDescriptor(
  name='BatteryStatus',
  full_name='ExistMessage.BatteryStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHARGING', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISCHARGING', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_CHARGING', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FULL', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=561,
  serialized_end=648,
)

_EXISTMESSAGE_BATTERYPLUGGED = _descriptor.EnumDescriptor(
  name='BatteryPlugged',
  full_name='ExistMessage.BatteryPlugged',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNPLUGGED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AC', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USB', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WIRELESS', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=650,
  serialized_end=712,
)

_EXISTMESSAGE_BATTERYHEALTH = _descriptor.EnumDescriptor(
  name='BatteryHealth',
  full_name='ExistMessage.BatteryHealth',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_HEALTH', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOOD', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OVERHEAT', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEAD', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OVER_VOLTAGE', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED_FAILURE', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLD', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=714,
  serialized_end=836,
)


_RAWLOCATIONMESSAGE = _descriptor.Descriptor(
  name='RawLocationMessage',
  full_name='RawLocationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='RawLocationMessage.device_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ts', full_name='RawLocationMessage.ts', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='RawLocationMessage.latitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='RawLocationMessage.longitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='RawLocationMessage.speed', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bearing', full_name='RawLocationMessage.bearing', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='RawLocationMessage.accuracy', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=161,
)


_EXISTMESSAGE = _descriptor.Descriptor(
  name='ExistMessage',
  full_name='ExistMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='ExistMessage.device_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ts', full_name='ExistMessage.ts', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battery_level', full_name='ExistMessage.battery_level', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battery_plugged', full_name='ExistMessage.battery_plugged', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battery_status', full_name='ExistMessage.battery_status', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battery_health', full_name='ExistMessage.battery_health', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battery_temperature', full_name='ExistMessage.battery_temperature', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_gps_time', full_name='ExistMessage.last_gps_time', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='ExistMessage.latitude', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='ExistMessage.longitude', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sent_time', full_name='ExistMessage.sent_time', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='communication', full_name='ExistMessage.communication', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mqtt', full_name='ExistMessage.mqtt', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_version', full_name='ExistMessage.app_version', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXISTMESSAGE_BATTERYSTATUS,
    _EXISTMESSAGE_BATTERYPLUGGED,
    _EXISTMESSAGE_BATTERYHEALTH,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=164,
  serialized_end=836,
)

_EXISTMESSAGE.fields_by_name['battery_plugged'].enum_type = _EXISTMESSAGE_BATTERYPLUGGED
_EXISTMESSAGE.fields_by_name['battery_status'].enum_type = _EXISTMESSAGE_BATTERYSTATUS
_EXISTMESSAGE.fields_by_name['battery_health'].enum_type = _EXISTMESSAGE_BATTERYHEALTH
_EXISTMESSAGE_BATTERYSTATUS.containing_type = _EXISTMESSAGE;
_EXISTMESSAGE_BATTERYPLUGGED.containing_type = _EXISTMESSAGE;
_EXISTMESSAGE_BATTERYHEALTH.containing_type = _EXISTMESSAGE;
DESCRIPTOR.message_types_by_name['RawLocationMessage'] = _RAWLOCATIONMESSAGE
DESCRIPTOR.message_types_by_name['ExistMessage'] = _EXISTMESSAGE

class RawLocationMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RAWLOCATIONMESSAGE

  # @@protoc_insertion_point(class_scope:RawLocationMessage)

class ExistMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXISTMESSAGE

  # @@protoc_insertion_point(class_scope:ExistMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\024com.via.avi.messagesB\013AviMessages')
# @@protoc_insertion_point(module_scope)
