-- enum types to mimic various GTFS-rt enums. See GTFS-rt spec for definitions
-- of these terms.

CREATE TYPE event_type AS
ENUM ('arrival', 'departure');

CREATE TYPE trip_schedule_relationship AS 
ENUM ('trip_scheduled', 'trip_added', 'trip_unscheduled', 'trip_canceled');

CREATE TYPE stop_time_schedule_relationship AS 
ENUM ('scheduled', 'skipped', 'no_data');

CREATE TYPE vehicle_stop_status AS
ENUM ('incoming_at', 'stopped_at', 'in_transit_to');

CREATE TYPE congestion_level AS 
ENUM ('unknown_congestion_level', 'running_smoothly', 'stop_and_go', 
     'congestion', 'severe_congestion');

CREATE TYPE battery_status AS
ENUM ('charging','discharging','full','not_charging','unknown');

CREATE TYPE battery_plugged AS
ENUM ('unplugged','ac','usb','wireless');

CREATE TYPE battery_health AS
ENUM ('unknown_health','good','overheat','dead','over_voltage',
'unspecified_failure','cold');

-- Datatypes generated by AVI Vehicle Tracker

CREATE TABLE raw_location (
       -- Auto-increment id for raw location messages:
       id SERIAL PRIMARY KEY,
       -- Android serial number or equivalent:
       device_id TEXT NOT NULL,
       ts TIMESTAMPTZ NOT NULL,
       -- WGS84 latitude (-90 to 90 degrees):
       latitude DOUBLE PRECISION,
       -- WGS84 longitude (0 to 360 east from prime meridian):
       longitude DOUBLE PRECISION,
       -- Speed in m/s:
       speed REAL,
       -- Bearing in degrees east of north:
       bearing REAL,
       -- Accuracy in meters:
       accuracy REAL,
       -- Timestamp at which location is inserted into database
       insert_ts TIMESTAMPTZ DEFAULT current_timestamp
);

CREATE INDEX rawloc_ts ON raw_location (ts);
CREATE INDEX rawloc_device_ts ON raw_location (device_id, ts);

CREATE TABLE exist (
       -- Auto-increment primary key:
       id SERIAL PRIMARY KEY,
       -- Android serial number or equivalent
       device_id TEXT,
       -- Timestamps of message generation:
       ts TIMESTAMPTZ NOT NULL,

       -- battery info:
       battery_level REAL,
       battery_plugged battery_plugged,
       battery_status battery_status,
       battery_health battery_health,
       battery_temperature INTEGER,

       -- GPS info:
       last_gps_time TIMESTAMPTZ,
       latitude DOUBLE PRECISION,
       longitude DOUBLE PRECISION,

       -- connectivity info:
       sent_time TIMESTAMPTZ,
       communication BOOLEAN,
       mqtt BOOLEAN,

       app_version TEXT,
       -- Timestamp at which exist message is actually inserted into database
       insert_ts TIMESTAMPTZ DEFAULT current_timestamp
);
CREATE INDEX exist_ts ON exist (ts);
CREATE INDEX exist_device_ts ON exist (device_id, ts);


-- Datatypes generated by AVI Server

-- Fields to store all information potentially associated with a GTFS-rt
-- VehiclePosition entity.

CREATE TABLE projected_location (
       -- Auto-increment id for projected location messages:
       id SERIAL PRIMARY KEY,
       -- Android serial number or equivalent:
       device_id TEXT,
       ts TIMESTAMPTZ NOT NULL,
       -- WGS84 latitude (-90 to 90 degrees):
       latitude DOUBLE PRECISION,
       -- WGS84 longitude (0 to 360 east from prime meridian):
       longitude DOUBLE PRECISION,
       -- Speed in m/s:
       speed REAL,
       -- Bearing in degrees east of north:
       bearing REAL,
       -- Accuracy in meters:
       accuracy REAL,
       
       -- Distance along route in meters:
       postmile REAL,
       -- Delay relative to schedule in milliseconds:
       delay bigint,
       -- Unique driver identifier:
       driver_id TEXT,
       -- Unique vehicle identifier:
       vehicle_id TEXT,
       -- GTFS trip ID:
       trip_id TEXT,
       -- GTFS route ID:
       route_id TEXT,
       -- Scheduled start time of this trip instance, in HH:MM:SS
       -- (corresponding to GTFS-rt).
       start_time TEXT,
       -- Scheduled start date of this trip instance, in YYYYMMDD
       -- (corresponding to GTFS-rt).
       start_date TEXT,
       -- Field indicating the relationship between this trip and the static 
       -- schedule:
       trip_schedule_relationship trip_schedule_relationship,
       
       -- Information about previous/current/upcoming GTFS stop:
       stop_id TEXT,
       current_stop_sequence integer,
       stop_latitude DOUBLE PRECISION,
       stop_longitude DOUBLE PRECISION,
       stop_postmile REAL,
       current_status vehicle_stop_status,
       
       congestion congestion_level,
       odometer REAL,
       -- Timestamp at which location is inserted into database
       insert_ts TIMESTAMPTZ DEFAULT current_timestamp
);
CREATE INDEX projloc_ts ON projected_location (ts);
CREATE INDEX projloc_device_ts ON projected_location (device_id,ts);
CREATE INDEX projloc_vehicle_ts ON projected_location (vehicle_id,ts);


-- Fields to store all information potential associated with a GTFS-rt
-- TripUpdate entity. Logically, however, these events represent 
-- arrival/departure events that have actually happened, rather than
-- predictions for future arrivals/departures.

CREATE TABLE event (
       -- Auto-increment primary key:
       id SERIAL PRIMARY KEY,
       -- Postgres timestamp type (equivalent to unix epoch timestamp but easier to work with)
       ts TIMESTAMPTZ NOT NULL,
       -- Android serial number or equivalent
       device_id TEXT,
       event_type event_type NOT NULL,
       -- Arrival or departure delay in milliseconds relative to GTFS schedule:
       delay integer,
       vehicle_id TEXT,
       driver_id TEXT,

       -- information about GTFS StopTime
       stop_id TEXT NOT NULL,
       stop_sequence integer,
       stop_latitude DOUBLE PRECISION,
       stop_longitude DOUBLE PRECISION,
       stop_postmile REAL,

       -- information about GTFS Trip
       trip_id TEXT,
       route_id TEXT,
       uncertainty integer,
       -- Field indicating the relationship between this trip and the static 
       -- schedule:
       trip_schedule_relationship trip_schedule_relationship,
       -- Field indicating the relationship between this event and the static 
       -- StopTime:
       stop_time_schedule_relationship stop_time_schedule_relationship,
       -- Scheduled start time of this trip instance, in HH:MM:SS
       start_time TEXT,
       -- Scheduled start date of this trip instance, in YYYYMMDD
       start_date TEXT,
       -- Timestamp at which event is inserted into database
       insert_ts TIMESTAMPTZ DEFAULT current_timestamp
);
CREATE INDEX event_ts ON event (ts);
CREATE INDEX event_device_ts ON event (device_id, ts);
CREATE INDEX event_vehicle_ts ON event (vehicle_id, ts);
CREATE INDEX event_route_ts ON event (route_id, ts);
CREATE INDEX event_stop_ts ON event (stop_id, ts);
